/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetype.addressbook.repositories;

import java.util.*;
import java.time.*;


import com.archetype.addressbook.domain.Contact;
import org.springframework.data.repository.*;
import org.springframework.stereotype.Repository;
// ----------- << imports@AAAAAAFrhExAeE6gAR0= >>
// ----------- >>

// ----------- << repository.annotations@AAAAAAFrhExAeE6gAR0= >>
// ----------- >>
@Repository
public interface ContactRepository extends CrudRepository<Contact, Long> {
// ----------- << repository.methods@AAAAAAFrhExAeE6gAR0= >>
// ----------- >>
}