/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetype.addressbook.domain;

import java.util.*;
import java.time.*;

import javax.persistence.*;
import javax.validation.constraints.*;


// ----------- << imports@AAAAAAFrhFWggk/jo4M= >>
// ----------- >>

@Entity
// ----------- << class.annotations@AAAAAAFrhFWggk/jo4M= >>
// ----------- >>
public class Address extends Contact {
	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAFrhFhBMlEzTbY= >>
	// ----------- >>
	private String streetAndNo;

	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAFrhFhTw1E6HKk= >>
	// ----------- >>
	private String city;

	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAFrhFhsYFFBz5g= >>
	// ----------- >>
	private String postalCode;

	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAFrhFh96lFI8MA= >>
	// ----------- >>
	private String country;

	public String getStreetAndNo() {
		return streetAndNo;
	}

	public String getCity() {
		return city;
	}

	public String getPostalCode() {
		return postalCode;
	}

	public String getCountry() {
		return country;
	}

	public Address setStreetAndNo(String streetAndNo) {
		this.streetAndNo = streetAndNo;
		return this;
	}

	public Address setCity(String city) {
		this.city = city;
		return this;
	}

	public Address setPostalCode(String postalCode) {
		this.postalCode = postalCode;
		return this;
	}

	public Address setCountry(String country) {
		this.country = country;
		return this;
	}

	// ----------- << equals.annotations@AAAAAAFrhFWggk/jo4M= >>
	// ----------- >>
	@Override
	public boolean equals(Object obj) {
		if (super.equals(obj)) return true;
		if (getId() == null) return false;
		return obj instanceof Address && (getId().equals(((Address) obj).getId()));
	}

	// ----------- << hashCode.annotations@AAAAAAFrhFWggk/jo4M= >>
	// ----------- >>
	@Override
	public int hashCode() {
		return 650;
	}

// ----------- << class.extras@AAAAAAFrhFWggk/jo4M= >>
// ----------- >>
}