/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetype.addressbook.domain;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFrhE3c609NVds= >>
// ----------- >>

/**
* Different kinds of Contact Categories
*/

// ----------- << class.annotations@AAAAAAFrhE3c609NVds= >>
// ----------- >>
public enum ContactCategory {
	mobile,
	work,
	main,
	home,
	workFax,
	homeFax,
	other;

// ----------- << enum.extras@AAAAAAFrhE3c609NVds= >>
// ----------- >>
}