/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetype.addressbook.domain;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFrhFduGlDdi2w= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFrhFduGlDdi2w= >>
// ----------- >>
public enum IMKind {
	aol,
	whatsApp,
	viber,
	skype,
	facebook,
	instagram;

// ----------- << enum.extras@AAAAAAFrhFduGlDdi2w= >>
// ----------- >>
}