/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetype.addressbook.domain;

import java.util.*;
import java.time.*;

import javax.persistence.*;
import javax.validation.constraints.*;


// ----------- << imports@AAAAAAFrhFWo2VA1e/o= >>
// ----------- >>

@Entity
// ----------- << class.annotations@AAAAAAFrhFWo2VA1e/o= >>
// ----------- >>
public class InstantMessenger extends Contact {
	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAFrhFcVDlDWsg0= >>
	// ----------- >>
	private String im;

	@Enumerated(EnumType.STRING)
	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAFrhFfuoFEqG8k= >>
	// ----------- >>
	private IMKind imKind;

	public String getIm() {
		return im;
	}

	public IMKind getImKind() {
		return imKind;
	}

	public InstantMessenger setIm(String im) {
		this.im = im;
		return this;
	}

	public InstantMessenger setImKind(IMKind imKind) {
		this.imKind = imKind;
		return this;
	}

	// ----------- << equals.annotations@AAAAAAFrhFWo2VA1e/o= >>
	// ----------- >>
	@Override
	public boolean equals(Object obj) {
		if (super.equals(obj)) return true;
		if (getId() == null) return false;
		return obj instanceof InstantMessenger && (getId().equals(((InstantMessenger) obj).getId()));
	}

	// ----------- << hashCode.annotations@AAAAAAFrhFWo2VA1e/o= >>
	// ----------- >>
	@Override
	public int hashCode() {
		return 204;
	}

// ----------- << class.extras@AAAAAAFrhFWo2VA1e/o= >>
// ----------- >>
}