/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetype.addressbook.domain;

import java.util.*;
import java.time.*;

import javax.persistence.*;
import javax.validation.constraints.*;


// ----------- << imports@AAAAAAFrhE1g7U7K2Ag= >>
// ----------- >>

@Entity
// ----------- << class.annotations@AAAAAAFrhE1g7U7K2Ag= >>
// ----------- >>
public class Phone extends Contact {
	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAFrhFaPdlC8Xrg= >>
	// ----------- >>
	private String phoneNo;

	public String getPhoneNo() {
		return phoneNo;
	}

	public Phone setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
		return this;
	}

	// ----------- << equals.annotations@AAAAAAFrhE1g7U7K2Ag= >>
	// ----------- >>
	@Override
	public boolean equals(Object obj) {
		if (super.equals(obj)) return true;
		if (getId() == null) return false;
		return obj instanceof Phone && (getId().equals(((Phone) obj).getId()));
	}

	// ----------- << hashCode.annotations@AAAAAAFrhE1g7U7K2Ag= >>
	// ----------- >>
	@Override
	public int hashCode() {
		return 640;
	}

// ----------- << class.extras@AAAAAAFrhE1g7U7K2Ag= >>

	public Phone(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	public Phone() {
	}

// ----------- >>
}