/*
* This code has been generated by the Rebel: a code generator for modern Java.
* 
* For more details, please visit www.archetypesoftware.com.
*
* Drop us a line or two at feedback@archetypesoftware.com. We would love to hear from you.
*/
package com.archetype.addressbook.domain;

import java.util.*;
import java.time.*;

import javax.persistence.*;
import javax.validation.constraints.*;


// ----------- << imports@AAAAAAFrhFWlTVAMLCM= >>
// ----------- >>

@Entity
// ----------- << class.annotations@AAAAAAFrhFWlTVAMLCM= >>
// ----------- >>
public class Website extends Contact {
	@NotNull
	@Column(nullable = false)
	// ----------- << attribute.annotations@AAAAAAFrhFb8DFDPMOs= >>
	// ----------- >>
	private String url;

	public String getUrl() {
		return url;
	}

	public Website setUrl(String url) {
		this.url = url;
		return this;
	}

	// ----------- << equals.annotations@AAAAAAFrhFWlTVAMLCM= >>
	// ----------- >>
	@Override
	public boolean equals(Object obj) {
		if (super.equals(obj)) return true;
		if (getId() == null) return false;
		return obj instanceof Website && (getId().equals(((Website) obj).getId()));
	}

	// ----------- << hashCode.annotations@AAAAAAFrhFWlTVAMLCM= >>
	// ----------- >>
	@Override
	public int hashCode() {
		return 230;
	}

// ----------- << class.extras@AAAAAAFrhFWlTVAMLCM= >>

	public Website(@NotNull String url) {
		this.url = url;
	}

	public Website() {
	}

// ----------- >>
}